name=ST7567Display
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Graphics display driver for 12864 LCDs with a Sitronix ST7567 SPI controller.
paragraph=** PRELIMINARY **
category=Display
includes=ST7567Display.h
url=https://github.com/mumanchu/ST7567Display
architectures=*
